persona.eliminada.ok=Empleado eliminada correctamente
persona.vacio=Empleado viene nulo
persona.rut.nulo=El rut es obligatorio
persona.rut.existe=Ya existe empleado con ese rut
persona.salario.limite=Salario debe ser mayor a $400.000
persona.id.no.existe=No eliminado, id empleado no existe

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# H2
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=prueba
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
